debug: true
server:
  port: 8080
#  ribbon:
#    eureka:
#      enabled: true
#    ServerListRefreshInterval: 1000
spring:
  application:
    name: ip-filter-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql:
  h2:
    console:
      enabled: true
      path: /h2
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: dbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    healthcheck:
#      enabled: true
#  instance:
#    preferIpAddress: true